name: DeployServerAndRunDeployScript
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Working dir
      run: pwd
    - uses: actions/checkout@v1
    - name: Build vue app
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build
    - run: cp ./deploy.sh ./dist/ 
    - name: Copy files over ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: ./dist
        remote: "/tmp/jmr-squared-website"
        host: ${{ secrets.SERVER_URL }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
    - name: Start container on remote server
      uses: garygrossgarten/github-action-ssh@v0.4.3
      with:
        command: "mkdir -p /tmp/jmr-squared-website && cd /tmp/jmr-squared-website && bash ./deploy.sh"
        host: ${{ secrets.SERVER_URL }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
